// sample local government areas
export default [
  { label: 'Afijio', value: 'Afijio' },
  { label: 'Ibadan North', value: 'Ibadan North' },
  { label: 'Ibadan North-East', value: 'Ibadan North-East' },
  { label: 'Ibadan North-West', value: 'Ibadan North-West' },
  { label: 'Ibadan South-East', value: 'Ibadan South-East' },
  { label: 'Ibadan South-West', value: 'Ibadan South-West' },
  { label: 'Ibarapa Central', value: 'Ibarapa Central' },
  { label: 'Ibarapa East', value: 'Ibarapa East' },
  { label: 'Ibarapa North', value: 'Ibarapa North' },
  { label: 'Ido', value: 'Ido' },
  { label: 'Irepo', value: 'Irepo' },
  { label: 'Iseyin', value: 'Iseyin' },
  { label: 'Itesiwaju', value: 'Itesiwaju' },
  { label: 'Iwajowa', value: 'Iwajowa' },
  { label: 'Kajola', value: 'Kajola' },
  { label: 'Lagelu', value: 'Lagelu' },
  { label: 'Ogo Oluwa', value: 'Ogo Oluwa' },
  { label: 'Olorunsogo', value: 'Olorunsogo' },
  { label: 'Oluyole', value: 'Oluyole' },
  { label: 'Ona Ara', value: 'Ona Ara' },
  { label: 'Ore lope', value: 'Ore lope' },
  { label: 'Ori Ire', value: 'Ori Ire' },
  { label: 'Oyo East', value: 'Oyo East' },
  { label: 'Oyo West', value: 'Oyo West' },
];
